version: "1.29.2"
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
networks:
  jebouche_inception_network:
    driver: bridge

services:

  nginx:
    build: ./requirements/nginx
    container_name: my_nginx_c
    ports:
      - "8000:443"
    networks:
      - jebouche_inception_network

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: my_wordpress_c
  #   networks:
  #     - jebouche_inception_network
  
  # mariadb:
  #   build: ./requirements/mariadb
  #   container_name: my_mariadb_c
  #   networks:
  #     - jebouche_inception_network