version: "1"
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
networks:
  jebouche_inception_network:
    driver: bridge #same a default

services:

  nginx:
    build: ./srcs/requirements/nginx
    image: nginx
    container_name: nginx_c
    ports:
      - "8000:443"
    networks:
      - jebouche_inception_network
    restart: always
    # volumes:
    #   - wordpress-data:/var/www/html

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      # args:
      #   - name=value
    image: mariadb
    container_name: mariadb_c
    networks:
      - jebouche_inception_network
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
  
  wordpress:
    depends_on:
      - mariadb
    build: ./srcs/requirements/wordpress
    image: wordpress
    container_name: wordpress_c
    networks:
      - jebouche_inception_network
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - DOMAIN_NAME=${DOMAIN_NAME}
  

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jebouche/Cursus42/inception/temp_volumes/mariadb-data

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jebouche/Cursus42/inception/temp_volumes/wordpress-data

# can specify specific env vars to pass to the containers
