version: "1"
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
networks:
  jebouche_inception_network:
    driver: bridge #same a default

services:

  nginx:
    build: ./srcs/requirements/nginx
    image: nginx
    container_name: nginx_c
    ports:
      - "8000:443"
    networks:
      - jebouche_inception_network
    restart: always
    volumes:
      - wordpress_volume:/var/www/html

  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb
    container_name: mariadb_c
    networks:
      - jebouche_inception_network
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
  
  # wordpress:
  #   build: ./srcs/requirements/wordpress
  #   image: wordpress
  #   container_name: wordpress_c
  #   networks:
  #     - jebouche_inception_network
  #   restart: always
  #   volumes:
  #     - wordpress_volume:/var/www/html
  

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jebouche/Cursus42/inception/temp_volumes/mariadb-data

  # wordpress_volume:

# can specify specific env vars to pass to the containers
