version: "1"
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
networks:
  jebouche_inception_network:
    driver: bridge #same a default

services:

  nginx:
    build: ./srcs/requirements/nginx
    image: nginx
    container_name: nginx_c
    ports:
      - "8000:443"
    networks:
      - jebouche_inception_network
    restart: always
    # volumes:
    #   - wordpress_volume:/var/www/html

  # wordpress:
  #   build: ./srcs/requirements/wordpress
  #   image: wordpress
  #   container_name: wordpress_c
  #   networks:
  #     - jebouche_inception_network
  #   restart: always
  #   volumes:
  #     - wordpress_volume:/var/www/html
  
  # mariadb:
  #   build: ./srcs/requirements/mariadb
  #   image: mariadb
  #   container_name: mariadb_c
  #   networks:
  #     - jebouche_inception_network
  #   restart: always
  #   volumes:
  #     - mariadb_volume:/var/lib/mysql

volumes:
  wordpress_volume:
  mariadb_volume:

# can specify specific env vars to pass to the containers