FROM alpine:3.18.6

# RUN installs for php, php-fpm, wget, command line tools for wordpress

# RUN script for wordpress install (should clt for wp be done in here?)

EXPOSE 9000

# CMD run the stuffs
